# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code, run tests across different versions of node, and deploy on push to main.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  # Trigger the workflow on push to the main branch
  push:
    branches: [ "main" ]
  # Trigger the workflow on pull request to the main branch
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Use the latest Ubuntu environment
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Define the Node.js versions to be used in the matrix
        node-version: [14.x, 16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Step to check out the repository
    - uses: actions/checkout@v4

    # Step to set up the Node.js environment for the current version in the matrix
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Step to install dependencies using npm ci
    - run: npm ci

    # Step to build the project if a build script is present
    - run: npm run build --if-present

    # Step to run tests
    - run: npm test

    # Step to deploy if on push to main branch
    - name: Deploy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: ./deploy.sh
